<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ProductPerLeverancier;

class ProductPerLeverancierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ProductPerLeverancier::insert([
            [
                'leverancierId' => 1,
                'productId' => 1,
                'datumLevering' => '2023-04-09',
                'aantal' => 23,
                'datumEerstvolgendeLevering' => '2023-04-16',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 1,
                'productId' => 1,
                'datumLevering' => '2023-04-18',
                'aantal' => 21,
                'datumEerstvolgendeLevering' => '2023-04-25',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 1,
                'productId' => 2,
                'datumLevering' => '2023-04-09',
                'aantal' => 12,
                'datumEerstvolgendeLevering' => '2023-04-16',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 1,
                'productId' => 3,
                'datumLevering' => '2023-04-10',
                'aantal' => 11,
                'datumEerstvolgendeLevering' => '2023-04-17',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 2,
                'productId' => 4,
                'datumLevering' => '2023-04-14',
                'aantal' => 16,
                'datumEerstvolgendeLevering' => '2023-04-21',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 2,
                'productId' => 4,
                'datumLevering' => '2023-04-21',
                'aantal' => 23,
                'datumEerstvolgendeLevering' => '2023-04-28',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 2,
                'productId' => 5,
                'datumLevering' => '2023-04-14',
                'aantal' => 45,
                'datumEerstvolgendeLevering' => '2023-04-21',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 2,
                'productId' => 6,
                'datumLevering' => '2023-04-14',
                'aantal' => 30,
                'datumEerstvolgendeLevering' => '2023-04-21',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 3,
                'productId' => 7,
                'datumLevering' => '2023-04-12',
                'aantal' => 12,
                'datumEerstvolgendeLevering' => '2023-04-19',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 3,
                'productId' => 7,
                'datumLevering' => '2023-04-19',
                'aantal' => 23,
                'datumEerstvolgendeLevering' => '2023-04-26',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 3,
                'productId' => 8,
                'datumLevering' => '2023-04-10',
                'aantal' => 12,
                'datumEerstvolgendeLevering' => '2023-04-17',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 3,
                'productId' => 9,
                'datumLevering' => '2023-04-11',
                'aantal' => 1,
                'datumEerstvolgendeLevering' => '2023-04-18',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 4,
                'productId' => 10,
                'datumLevering' => '2023-04-16',
                'aantal' => 24,
                'datumEerstvolgendeLevering' => '2023-04-30',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 5,
                'productId' => 11,
                'datumLevering' => '2023-04-10',
                'aantal' => 47,
                'datumEerstvolgendeLevering' => '2023-04-17',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 5,
                'productId' => 11,
                'datumLevering' => '2023-04-19',
                'aantal' => 60,
                'datumEerstvolgendeLevering' => '2023-04-26',
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 5,
                'productId' => 12,
                'datumLevering' => '2023-04-11',
                'aantal' => 45,
                'datumEerstvolgendeLevering' => NULL,
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'leverancierId' => 5,
                'productId' => 13,
                'datumLevering' => '2023-04-12',
                'aantal' => 23,
                'datumEerstvolgendeLevering' => NULL,
                'isActief' => 1,
                'opmerkingen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
